#define ESTADO_IDLE 0
#define ESTADO_CORRIENDO 1
#define ESTADO_DISPARANDO 2
#define ESTADO_MUERTO 3

#define ID_BLOQUE_PIEDRA 100
#define ID_BLOQUE_METAL 101
#define ID_BLOQUE_DIAGONAL_METAL 102
#define ID_PIEDRA 104
#define ID_ACIDO 105
#define ID_BOTON 106
#define ID_EMISOR 107
#define ID_RECEPTOR 108
#define ID_PUERTA 109
#define ID_BARRERA_ENERGIA 110
#define ID_PERSONAJE 111
#define ID_PASTEL 112
